# Generated by Django 3.1.7 on 2021-02-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_fleet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fleet',
        ),
    ]
