# Generated by Django 3.1.7 on 2021-02-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0004_delete_fleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='fleet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fishName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
