# Generated by Django 3.1.7 on 2021-02-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_subfleet'),
    ]

    operations = [
        migrations.CreateModel(
            name='wholesaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('subfleetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.subfleet')),
            ],
        ),
        migrations.CreateModel(
            name='retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('wholesalerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.wholesaler')),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('retailerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.retailer')),
            ],
        ),
    ]
