# Generated by Django 3.1.7 on 2021-02-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0008_auto_20210301_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='afleet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fishName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bsubfleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('fleetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.afleet')),
            ],
        ),
        migrations.CreateModel(
            name='cwholesaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('subfleetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.bsubfleet')),
            ],
        ),
        migrations.CreateModel(
            name='dretailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('wholesalerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.cwholesaler')),
            ],
        ),
        migrations.CreateModel(
            name='econsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('retailerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.dretailer')),
            ],
        ),
    ]
