# Generated by Django 3.1.7 on 2021-02-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_afleet_bsubfleet_cwholesaler_dretailer_econsumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bsubfleet',
            name='fleetid',
        ),
        migrations.RemoveField(
            model_name='cwholesaler',
            name='subfleetid',
        ),
        migrations.RemoveField(
            model_name='dretailer',
            name='wholesalerid',
        ),
        migrations.RemoveField(
            model_name='econsumer',
            name='retailerid',
        ),
        migrations.DeleteModel(
            name='afleet',
        ),
        migrations.DeleteModel(
            name='bsubfleet',
        ),
        migrations.DeleteModel(
            name='cwholesaler',
        ),
        migrations.DeleteModel(
            name='dretailer',
        ),
        migrations.DeleteModel(
            name='econsumer',
        ),
    ]
