# Generated by Django 3.1.7 on 2021-03-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0020_a_fleet_b_subfleet_c_wholesaler_d_retailer_e_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_fleet',
            name='blockchain_addr',
            field=models.CharField(default='d751c520911462e35a5cb81db9aa762cb2fc9572ba448c3f7989d93a8486f52b', max_length=32),
        ),
    ]
