# Generated by Django 3.1.7 on 2021-03-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0021_auto_20210306_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_fleet',
            name='blockchain_addr',
            field=models.CharField(default='591d5212f9e91482bb72fd3bdec90f5c1f7edf0dfd34d0e21592f42e057ff79e', max_length=32),
        ),
    ]
