# Generated by Django 3.1.7 on 2021-03-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_auto_20210306_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_fleet',
            name='blockchain_addr',
            field=models.CharField(default='6e8429a51fb089890b60fbb54d209fb74af8dca3c91cee0bfa5ab453d883cd99', max_length=64),
        ),
    ]
